name: build
on:
  pull_request: {}
  push: {}
  workflow_dispatch: {}

jobs:
  build:
    strategy:
      matrix:
        java: [ 17 ]
    runs-on: ubuntu-latest
    steps:
      - name: checkout repository
        uses: https://git.bitheaven.ru/actions/checkout@v2

      - name: setup jdk ${{ matrix.java }}
        uses: https://git.bitheaven.ru/actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}

      - uses: https://git.bitheaven.ru/actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/loom-cache
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: make gradle wrapper executable
        run: chmod +x ./gradlew

      - name: build
        run: ./gradlew build

      - name: capture build artifacts
        uses: https://git.bitheaven.ru/actions/upload-artifact@v2
        with:
          name: Artifacts
          path: build/libs/
